spring:
  datasource:
    url: jdbc:postgresql://${DB_POSTGRE_HOST:localhost}:${DB_POSTGRE_PORT:5432}/pizza-delivery
    username: ${DB_POSTGRE_USER:postgre}
    password: ${DB_POSTGRE_PASS:pass}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect