spring:
  datasource:
    url: jdbc:h2:mem:pizza-delivery
    driverClassName: "org.h2.Driver"
    username: ${DB_H2_USER:h2}
    password: ${DB_H2_PASS:pass}
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  h2:
    console:
      enabled: true
