app:
  items-on-page: 6

spring:
  datasource:
    url: jdbc:h2:mem:pizza
    username: name
    password: pass
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html